name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install depot_tools
        run: |
          sudo apt-get install git curl xz-utils python3-pkg-resources python3-virtualenv python3-oauth2client
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "PATH=$(pwd)/depot_tools:$PATH" >> $GITHUB_ENV
      - name: Build chii
        run: |
          npm i -g @liriliri/lsla
          npm i
          npm run build
